In [76]:
import pandas as pd

In [77]:
df=pd.read_csv('imdb_top_1000.csv')

In [78]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [79]:
df.shape

(1000, 16)

In [80]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [81]:
df.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [83]:
df=df.drop(columns='Poster_Link',axis=1)

In [84]:
df.shape

(1000, 15)

In [85]:
df['Overview'].head()

0    Two imprisoned men bond over a number of years...
1    An organized crime dynasty's aging patriarch t...
2    When the menace known as the Joker wreaks havo...
3    The early life and career of Vito Corleone in ...
4    A jury holdout attempts to prevent a miscarria...
Name: Overview, dtype: object

In [86]:
df['Content']=df['Series_Title'] +" " + df['Overview']

In [87]:
df['Content']

0      The Shawshank Redemption Two imprisoned men bo...
1      The Godfather An organized crime dynasty's agi...
2      The Dark Knight When the menace known as the J...
3      The Godfather: Part II The early life and care...
4      12 Angry Men A jury holdout attempts to preven...
                             ...
995    Breakfast at Tiffany's A young New York social...
996    Giant Sprawling epic covering the life of a Te...
997    From Here to Eternity In Hawaii in 1941, a pri...
998    Lifeboat Several survivors of a torpedoed merc...
999    The 39 Steps A man in London tries to help a c...
Name: Content, Length: 1000, dtype: object

In [88]:
df.duplicated().sum()

0

In [114]:
df.isnull().sum()

Series_Title       0
Released_Year      0
Certificate      999
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross              0
Content            0
dtype: int64

In [115]:
df['Certificate'].unique()

array(['U', nan], dtype=object)

In [116]:
df['Certificate']=df['Certificate'].fillna(df['Certificate'],'unknown')

TypeError: NDFrame.fillna() takes from 1 to 2 positional arguments but 3 were given

In [90]:
df['Gross']=df['Gross'].str.replace(',','',regex=False)

In [91]:
df['Gross']=pd.to_numeric(df['Gross'],errors='coerce')

In [92]:
df['Gross']

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            NaN
996            NaN
997     30500000.0
998            NaN
999            NaN
Name: Gross, Length: 1000, dtype: float64

In [93]:
df['Gross'] = df['Gross'].fillna(df['Gross'].median())

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Certificate    899 non-null    object
 3   Runtime        1000 non-null   object
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   object
 7   Meta_score     843 non-null    float64
 8   Director       1000 non-null   object
 9   Star1          1000 non-null   object
 10  Star2          1000 non-null   object
 11  Star3          1000 non-null   object
 12  Star4          1000 non-null   object
 13  No_of_Votes    1000 non-null   int64
 14  Gross          1000 non-null   float64
 15  Content        1000 non-null   object
dtypes: float64(3), int64(1), object(12)
memory usage: 125.1+ KB

In [95]:
X=df[['Content']]
y=df['Gross']

In [96]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [97]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X, y,train_size=0.8,random_state=42)

In [98]:
model_V=TfidfVectorizer()

In [99]:
Xtrain_vec = model_V.fit_transform(Xtrain['Content'])
Xtest_vec = model_V.transform(Xtest['Content'])

In [100]:
from sklearn.tree import DecisionTreeRegressor

In [101]:
model=DecisionTreeRegressor(random_state=42)

In [102]:
model.fit(Xtrain_vec,ytrain)

DecisionTreeRegressor(random_state=42)

In [103]:
ypred_train = model.predict(Xtrain_vec)
ypred_test = model.predict(Xtest_vec)

In [104]:
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error

In [105]:
print('TRAIN: ')
print('r2_score: ',r2_score(ytrain,ypred_train))  
print('MAE: ',mean_absolute_error(ytrain,ypred_train))
print('RMSE: ',root_mean_squared_error(ytrain,ypred_train))

TRAIN:
r2_score:  1.0
MAE:  0.0
RMSE:  0.0

In [106]:
print('TEST: ')
print('r2_score: ',r2_score(ytest,ypred_test))
print('MAE: ',mean_absolute_error(ytest,ypred_test))
print('RMSE: ',root_mean_squared_error(ytest,ypred_test))

TEST:
r2_score:  -0.5611372330284223
MAE:  75176519.52
RMSE:  143935504.3392011