In [109]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from category_encoders import TargetEncoder

In [110]:
df=pd.read_csv('playtennis.csv')

In [111]:
df

      Outlook Temperature Humidity    Wind PlayTennis
0       Sunny         Hot     High    Weak         No
1    Overcast        Mild   Normal  Strong         No
2    Overcast        Cool   Normal     NaN        Yes
3        Rain        Mild     High  Strong         No
4        Rain         Hot   Normal    Weak        Yes
..        ...         ...      ...     ...        ...
195      Rain        Mild     High    Weak        Yes
196  Overcast         Hot     High  Strong        Yes
197     Sunny        Mild   Normal  Strong        Yes
198      Rain        Mild     High    Weak        Yes
199      Rain        Cool     High    Weak         No

[200 rows x 5 columns]

In [112]:
df['Wind']=df['Wind'].fillna(df['Wind'].mode()[0])

In [113]:
df['Humidity']=df['Humidity'].fillna(df['Humidity'].mode()[0])

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      200 non-null    object
 1   Temperature  200 non-null    object
 2   Humidity     200 non-null    object
 3   Wind         200 non-null    object
 4   PlayTennis   200 non-null    object
dtypes: object(5)
memory usage: 7.9+ KB

In [115]:
X=df.drop(columns='PlayTennis')
y=df['PlayTennis']

In [116]:
X

      Outlook Temperature Humidity    Wind
0       Sunny         Hot     High    Weak
1    Overcast        Mild   Normal  Strong
2    Overcast        Cool   Normal    Weak
3        Rain        Mild     High  Strong
4        Rain         Hot   Normal    Weak
..        ...         ...      ...     ...
195      Rain        Mild     High    Weak
196  Overcast         Hot     High  Strong
197     Sunny        Mild   Normal  Strong
198      Rain        Mild     High    Weak
199      Rain        Cool     High    Weak

[200 rows x 4 columns]

In [117]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,train_size=0.8,random_state=42)

In [118]:
for word in df.columns:
    print('\n',word)
    print(df[word].unique())

 Outlook
['Sunny' 'Overcast' 'Rain']

 Temperature
['Hot' 'Mild' 'Cool']

 Humidity
['High' 'Normal']

 Wind
['Weak' 'Strong']

 PlayTennis
['No' 'Yes']

In [119]:
Xtrain['Humidity'].unique()

array(['High', 'Normal'], dtype=object)

In [120]:
order=[ 'Normal','High']

In [121]:
C_transformer=ColumnTransformer(
    transformers=[
                  ('One_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),['Outlook','Wind']),
                  ('ordinal',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1,categories=[order,[ 'Cool','Mild','Hot']]),['Humidity','Temperature'])
                  ],remainder='passthrough'
    )

In [122]:
C_transformer.fit_transform(Xtrain,ytrain)

array([[0., 1., 0., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 2.],
       ...,
       [0., 1., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 2.]])

In [123]:
C_transformer.transform(Xtest)

array([[0., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1., 1.],
       [0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 2.],
       [1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 2.],
       [0., 0., 1., 0., 1., 1., 2.],
       [0., 0., 1., 0., 1., 0., 2.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 1.],
       [1., 0., 0., 1., 0., 1., 2.],
       [0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 1., 2.],
       [0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 2.],
       [0., 1., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1., 1., 1.],
       [0., 1., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 1., 2.],
       [1., 0., 0., 0., 1., 0., 2.],
       [0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 2.],
       [0., 0., 1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0.]])